### PR TITLE
Fix linter issues

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Follow-up to https://github.com/martinmunillas/otter/pull/3#discussion_r1844186236; see issues at https://github.com/martinmunillas/otter/actions/runs/11891523391/job/33132448175#step:3:25

### CODE REVIEW

**Comment by martinmunillas** [comment]
Thank you, @Mariscal6 wanted to fix them but I guess you beat him :)

**Comment by martinmunillas** [comment]
@0x2b3bfa0 do you have x/linkedin?

**Comment by 0x2b3bfa0** [comment]
No, @martinmunillas: I'm allergic to both. 😄 Depending on the nature of your question, you may want to consider GitHub, Gmail, Slack,[^1] Keybase,[^2] and [carrier pigeons](https://xkcd.com/1254/) as stalking/social/contact alternatives.

[^1]: Use https://gophers.slack.com, for instance
[^2]: Almost abandoned since the Zoom "acqhire" 😿

**Comment by martinmunillas** [comment]
I'm in the slack, what is your name?

**Comment by 0x2b3bfa0** [comment]
Captura de pantalla 2024-11-18 a las 15 18 59

**Pull request merged**
